In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from imblearn.over_sampling import ADASYN

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)

In [166]:
data=pd.read_csv("train.csv")

In [167]:
data.head()

   Age  Attrition  ...  Sales Executive  Sales Representative
0   58          0  ...                0                     0
1   45          0  ...                0                     0
2   40          0  ...                1                     0
3   36          0  ...                1                     0
4   25          1  ...                0                     1

[5 rows x 43 columns]

In [168]:
col=data.columns

In [169]:
col

Index(['Age', 'Attrition', 'BusinessTravel', 'DistanceFromHome', 'Education',
       'EnvironmentSatisfaction', 'Gender', 'JobInvolvement', 'JobLevel',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome',
       'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Dept-Human Resouces',
       'Dept-Research & Development', 'Dept-Sales',
       'EducationField-Human Resources', 'EducationField-Life Sciences',
       'EducationField-Marketing', 'EducationField-Medical',
       'EducationField-Other', 'EducationField-Technical Degree',
       'Healthcare Representative', 'Human Resources', 'Laboratory Technician',
       'Manager', 'Manufacturing Director', 'Research Director',
       'Research Scientist', 'Sales Executive', 'Sales Representative'],
      dtype='object')

In [170]:
data['Attrition'].value_counts()

0    988
1    188
Name: Attrition, dtype: int64

In [171]:
ada = ADASYN(sampling_strategy='minority', random_state= 420 , n_neighbors = 10)

In [172]:
y=data['Attrition']

In [173]:
X=data.drop(['Attrition'],axis=1)

In [174]:
X

      Age  BusinessTravel  ...  Sales Executive  Sales Representative
0      58               2  ...                0                     0
1      45               2  ...                0                     0
2      40               2  ...                1                     0
3      36               1  ...                1                     0
4      25               3  ...                0                     1
...   ...             ...  ...              ...                   ...
1171   34               2  ...                0                     1
1172   35               2  ...                0                     0
1173   43               2  ...                1                     0
1174   38               2  ...                0                     0
1175   40               2  ...                1                     0

[1176 rows x 42 columns]

In [175]:
data

      Age  Attrition  ...  Sales Executive  Sales Representative
0      58          0  ...                0                     0
1      45          0  ...                0                     0
2      40          0  ...                1                     0
3      36          0  ...                1                     0
4      25          1  ...                0                     1
...   ...        ...  ...              ...                   ...
1171   34          0  ...                0                     1
1172   35          0  ...                0                     0
1173   43          0  ...                1                     0
1174   38          0  ...                0                     0
1175   40          0  ...                1                     0

[1176 rows x 43 columns]

In [176]:
X_res, y_res = ada.fit_resample(X,y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)

In [177]:
X_res.shape

(1967, 42)

In [29]:
! pip install https://h2o-release.s3.amazonaws.com/h2o/rel-zermelo/5/Python/h2o-3.32.0.5-py2.py3-none-any.whl

Collecting h2o==3.32.0.5
  Downloading https://h2o-release.s3.amazonaws.com/h2o/rel-zermelo/5/Python/h2o-3.32.0.5-py2.py3-none-any.whl (164.7MB)
     |████████████████████████████████| 164.7MB 55kB/s
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (from h2o==3.32.0.5) (0.16.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from h2o==3.32.0.5) (2.23.0)
Collecting colorama>=0.3.8
  Downloading https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl
Requirement already satisfied: tabulate in /usr/local/lib/python3.7/dist-packages (from h2o==3.32.0.5) (0.8.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->h2o==3.32.0.5) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->h2o==3.32.0.5) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->h2o==3.32.0.5) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->h2o==3.32.0.5) (2020.12.5)
Installing collected packages: colorama, h2o
Successfully installed colorama-0.4.4 h2o-3.32.0.5

In [125]:
y_res

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [178]:
y_res.shape

(1967,)

In [179]:
y_res=y_res.reshape(1967,1)

In [180]:
a=np.concatenate((X_res,y_res),axis=1)

In [181]:
a.shape

(1967, 43)

In [182]:
d=pd.DataFrame(a)

In [183]:
d

      0   1   2   3   4   5   6   7   8   ...  34  35  36  37  38  39  40  41  42
0     58   2  21   3   4   0   3   4   4  ...   0   0   1   0   0   0   0   0   0
1     45   2  28   3   4   1   3   1   4  ...   0   0   0   0   0   1   0   0   0
2     40   2  26   3   3   1   3   2   1  ...   0   0   0   0   0   0   1   0   0
3     36   1   8   4   1   1   2   3   1  ...   0   0   0   0   0   0   1   0   0
4     25   3  24   1   3   1   1   1   4  ...   0   0   0   0   0   0   0   1   1
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..
1962  43   2   7   3   3   0   3   3   3  ...   0   0   0   0   0   0   0   0   1
1963  29   2  15   2   3   0   2   3   1  ...   0   0   0   0   0   0   0   0   1
1964  32   2   1   4   3   0   3   3   2  ...   0   0   0   0   0   0   0   0   1
1965  40   2   6   3   3   0   3   3   3  ...   0   0   0   0   0   0   0   0   1
1966  32   2   6   4   1   0   3   2   1  ...   0   0   0   0   0   0   0   0   1

[1967 rows x 43 columns]

In [184]:
l=list(data.columns)

In [185]:
l.remove("Attrition")

In [186]:
l

['Age',
 'BusinessTravel',
 'DistanceFromHome',
 'Education',
 'EnvironmentSatisfaction',
 'Gender',
 'JobInvolvement',
 'JobLevel',
 'JobSatisfaction',
 'MaritalStatus',
 'MonthlyIncome',
 'NumCompaniesWorked',
 'OverTime',
 'PercentSalaryHike',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'StockOptionLevel',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager',
 'Dept-Human Resouces',
 'Dept-Research & Development',
 'Dept-Sales',
 'EducationField-Human Resources',
 'EducationField-Life Sciences',
 'EducationField-Marketing',
 'EducationField-Medical',
 'EducationField-Other',
 'EducationField-Technical Degree',
 'Healthcare Representative',
 'Human Resources',
 'Laboratory Technician',
 'Manager',
 'Manufacturing Director',
 'Research Director',
 'Research Scientist',
 'Sales Executive',
 'Sales Representative']

In [187]:
l.append("Attrition")

In [188]:
len(l)

43

In [189]:
d.columns=l

In [190]:
d

      Age  BusinessTravel  ...  Sales Representative  Attrition
0      58               2  ...                     0          0
1      45               2  ...                     0          0
2      40               2  ...                     0          0
3      36               1  ...                     0          0
4      25               3  ...                     1          1
...   ...             ...  ...                   ...        ...
1962   43               2  ...                     0          1
1963   29               2  ...                     0          1
1964   32               2  ...                     0          1
1965   40               2  ...                     0          1
1966   32               2  ...                     0          1

[1967 rows x 43 columns]

In [140]:
np.sum(d["Attrition"])

236

In [63]:
! pip install https://h2o-release.s3.amazonaws.com/h2o/rel-zermelo/5/Python/h2o-3.32.0.5-py2.py3-none-any.whl

Requirement already satisfied: h2o==3.32.0.5 from https://h2o-release.s3.amazonaws.com/h2o/rel-zermelo/5/Python/h2o-3.32.0.5-py2.py3-none-any.whl in /usr/local/lib/python3.7/dist-packages (3.32.0.5)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from h2o==3.32.0.5) (2.23.0)
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (from h2o==3.32.0.5) (0.16.0)
Requirement already satisfied: colorama>=0.3.8 in /usr/local/lib/python3.7/dist-packages (from h2o==3.32.0.5) (0.4.4)
Requirement already satisfied: tabulate in /usr/local/lib/python3.7/dist-packages (from h2o==3.32.0.5) (0.8.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->h2o==3.32.0.5) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->h2o==3.32.0.5) (2020.12.5)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->h2o==3.32.0.5) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->h2o==3.32.0.5) (2.10)

In [64]:
import h2o
from h2o.automl import H2OAutoML

h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "11.0.10" 2021-01-19; OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.18.04); OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.7/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpjjgqij3t
  JVM stdout: /tmp/tmpjjgqij3t/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmpjjgqij3t/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  ------------------------------------------------------------------
H2O_cluster_uptime:         03 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.32.0.5
H2O_cluster_version_age:    12 days
H2O_cluster_name:           H2O_from_python_unknownUser_9ptui1
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.180 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         accepting new members, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, XGBoost, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.7.10 final
--------------------------  ------------------------------------------------------------------

In [141]:
d.to_csv("testadasyn.csv",index=False)

In [192]:
train = h2o.import_file("adasyn.csv")

Parse progress: |█████████████████████████████████████████████████████████| 100%

In [193]:
train

Age,BusinessTravel,DistanceFromHome,Education,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobSatisfaction,MaritalStatus,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Dept-Human Resouces,Dept-Research & Development,Dept-Sales,EducationField-Human Resources,EducationField-Life Sciences,EducationField-Marketing,EducationField-Medical,EducationField-Other,EducationField-Technical Degree,Healthcare Representative,Human Resources,Laboratory Technician,Manager,Manufacturing Director,Research Director,Research Scientist,Sales Executive,Sales Representative,Attrition
58,2,21,3,4,0,3,4,4,3,17875,4,1,13,3,3,1,29,2,2,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0
45,2,28,3,4,1,3,1,4,3,2132,4,0,20,4,4,1,8,3,3,5,4,0,3,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0
40,2,26,3,3,1,3,2,1,3,8396,1,0,14,3,2,1,8,3,2,7,7,7,5,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
36,1,8,4,1,1,2,3,1,1,7587,1,0,15,3,2,0,10,1,3,10,7,0,9,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
25,3,24,1,3,1,1,1,4,1,1118,1,1,14,3,4,0,1,4,3,1,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1
52,2,4,2,4,0,3,4,4,3,16555,2,0,13,3,4,0,31,2,1,5,2,1,4,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0
47,2,9,4,2,0,3,1,3,1,2105,4,0,12,3,3,0,7,2,3,2,2,2,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0
26,2,17,4,4,1,1,1,3,3,2305,1,0,15,3,3,3,3,3,4,3,2,0,2,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0
24,1,13,2,4,0,3,1,2,3,2033,1,0,13,3,3,1,1,2,3,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
27,2,1,2,3,0,3,3,1,3,7412,1,0,11,3,4,0,9,3,3,9,7,0,7,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [194]:
x = train.columns
y = "Attrition"
x.remove(y)

In [195]:
train[y] = train[y].asfactor()

In [72]:
aml = H2OAutoML(max_models=40, seed=1,verbosity="info")
aml.train(x=x, y=y, training_frame=train)

AutoML progress: |
08:29:03.806: Project: AutoML_20210329_82903802
08:29:03.816: Setting stopping tolerance adaptively based on the training frame: 0.0225474701184918
08:29:03.816: Build control seed: 1
08:29:03.818: training frame: Frame key: automl_training_py_2_sid_98ce    cols: 43    rows: 1967  chunks: 8    size: 76834  checksum: 1442117467069997515
08:29:03.818: validation frame: NULL
08:29:03.818: leaderboard frame: NULL
08:29:03.818: blending frame: NULL
08:29:03.818: response column: Attrition
08:29:03.819: fold column: null
08:29:03.819: weights column: null
08:29:03.858: Loading execution steps: [{XGBoost : defaults}, {GLM : defaults}, {DRF : [def_1]}, {GBM : defaults}, {DeepLearning : defaults}, {DRF : [XRT]}, {XGBoost : grids}, {GBM : grids}, {DeepLearning : grids}, {GBM : [lr_annealing]}, {XGBoost : [lr_search]}, {StackedEnsemble : defaults}]
08:29:03.882: AutoML job created: 2021.03.29 08:29:03.801
08:29:03.883: AutoML build started: 2021.03.29 08:29:03.882
08:29:03.904: AutoML: starting XGBoost_1_AutoML_20210329_082903 model training

██
08:29:13.954: New leader: XGBoost_1_AutoML_20210329_082903, auc: 0.9652412194547026
08:29:13.955: AutoML: starting XGBoost_2_AutoML_20210329_082903 model training

█
08:29:19.966: AutoML: starting XGBoost_3_AutoML_20210329_082903 model training

██
08:29:28.977: New leader: XGBoost_3_AutoML_20210329_082903, auc: 0.9703003974145311
08:29:28.980: AutoML: starting GLM_1_AutoML_20210329_082903 model training

██
08:29:38.991: AutoML: starting DRF_1_AutoML_20210329_082903 model training

█
08:29:49.26: New leader: DRF_1_AutoML_20210329_082903, auc: 0.9729088179709113
08:29:49.27: AutoML: starting GBM_1_AutoML_20210329_082903 model training

██
08:30:02.33: New leader: GBM_1_AutoML_20210329_082903, auc: 0.9751367792467733
08:30:02.33: AutoML: starting GBM_2_AutoML_20210329_082903 model training

█
08:30:13.42: New leader: GBM_2_AutoML_20210329_082903, auc: 0.9756759355369645
08:30:13.42: AutoML: starting GBM_3_AutoML_20210329_082903 model training

██
08:30:24.61: New leader: GBM_3_AutoML_20210329_082903, auc: 0.9758661651772237
08:30:24.61: AutoML: starting GBM_4_AutoML_20210329_082903 model training

██
08:30:36.75: New leader: GBM_4_AutoML_20210329_082903, auc: 0.9761990670476773
08:30:36.76: AutoML: starting GBM_5_AutoML_20210329_082903 model training

█
08:30:50.100: AutoML: starting DeepLearning_1_AutoML_20210329_082903 model training

█
08:30:54.146: AutoML: starting XRT_1_AutoML_20210329_082903 model training

██
08:31:03.162: AutoML: starting XGBoost_grid__1_AutoML_20210329_082903 hyperparameter search

████████████
08:32:25.570: AutoML: starting GBM_grid__1_AutoML_20210329_082903 hyperparameter search

█████
08:32:46.654: New leader: GBM_grid__1_AutoML_20210329_082903_model_2, auc: 0.9767030722086901

███
08:33:23.821: New leader: GBM_grid__1_AutoML_20210329_082903_model_5, auc: 0.9784001480482852

██
08:33:43.921: New leader: GBM_grid__1_AutoML_20210329_082903_model_7, auc: 0.9818061890799915

█
08:33:52.937: AutoML: starting DeepLearning_grid__1_AutoML_20210329_082903 hyperparameter search

█████████████
09:01:20.334: AutoML: starting DeepLearning_grid__2_AutoML_20210329_082903 hyperparameter search

█
09:29:56.787: AutoML: starting DeepLearning_grid__3_AutoML_20210329_082903 hyperparameter search


09:50:45.212: AutoML: starting StackedEnsemble_BestOfFamily_AutoML_20210329_082903 model training
09:50:46.258: AutoML: starting StackedEnsemble_AllModels_AutoML_20210329_082903 model training

| 100%

09:50:50.318: No base models, due to timeouts or the exclude_algos option. Skipping StackedEnsemble 'monotonic'.
09:50:50.319: Actual modeling steps: [{XGBoost : [def_1 (10), def_2 (10), def_3 (10)]}, {GLM : [def_1 (10)]}, {DRF : [def_1 (10)]}, {GBM : [def_1 (10), def_2 (10), def_3 (10), def_4 (10), def_5 (10)]}, {DeepLearning : [def_1 (10)]}, {DRF : [XRT (10)]}, {XGBoost : [grid_1 (100)]}, {GBM : [grid_1 (60)]}, {DeepLearning : [grid_1 (20), grid_2 (20), grid_3 (20)]}, {StackedEnsemble : [best (10), all (10)]}]
09:50:50.319: AutoML build stopped: 2021.03.29 09:50:50.319
09:50:50.319: AutoML build done: built 42 models
09:50:50.319: AutoML duration:  1:21:46.437

In [73]:
lb = aml.leaderboard
lb.head(rows=lb.nrows)

model_id,auc,logloss,aucpr,mean_per_class_error,rmse,mse
GBM_grid__1_AutoML_20210329_082903_model_7,0.981806,0.168059,0.984569,0.0635941,0.221985,0.0492773
StackedEnsemble_BestOfFamily_AutoML_20210329_082903,0.979311,0.172748,0.983461,0.0605716,0.221044,0.0488605
StackedEnsemble_AllModels_AutoML_20210329_082903,0.978946,0.176938,0.983093,0.0625726,0.224018,0.0501842
GBM_grid__1_AutoML_20210329_082903_model_5,0.9784,0.185099,0.981509,0.0687013,0.231168,0.0534388
GBM_grid__1_AutoML_20210329_082903_model_2,0.976703,0.186593,0.980696,0.0687246,0.233966,0.0547399
GBM_4_AutoML_20210329_082903,0.976199,0.18651,0.980976,0.0646016,0.231013,0.0533672
GBM_3_AutoML_20210329_082903,0.975866,0.189103,0.980545,0.0718215,0.234581,0.0550284
GBM_2_AutoML_20210329_082903,0.975676,0.189438,0.980097,0.0713247,0.234784,0.0551234
GBM_grid__1_AutoML_20210329_082903_model_4,0.975642,0.189908,0.980566,0.0707815,0.234986,0.0552184
GBM_1_AutoML_20210329_082903,0.975137,0.191687,0.979807,0.0737946,0.236565,0.0559631
GBM_grid__1_AutoML_20210329_082903_model_1,0.97461,0.196541,0.979059,0.0733118,0.240254,0.057722
XGBoost_grid__1_AutoML_20210329_082903_model_3,0.97364,0.200167,0.978675,0.0703266,0.240526,0.0578526
XGBoost_grid__1_AutoML_20210329_082903_model_11,0.973102,0.201998,0.978166,0.0717564,0.24275,0.0589276
XGBoost_grid__1_AutoML_20210329_082903_model_10,0.972995,0.199953,0.978249,0.0697647,0.241359,0.0582541
DRF_1_AutoML_20210329_082903,0.972909,0.275611,0.977265,0.0763296,0.27674,0.076585
XGBoost_grid__1_AutoML_20210329_082903_model_12,0.971729,0.211281,0.976048,0.0804387,0.251509,0.0632569
GBM_grid__1_AutoML_20210329_082903_model_3,0.971049,0.217886,0.976928,0.0733909,0.249104,0.0620526
XGBoost_3_AutoML_20210329_082903,0.9703,0.212927,0.976003,0.0788647,0.249694,0.0623469
XGBoost_grid__1_AutoML_20210329_082903_model_7,0.968085,0.235618,0.974413,0.0825002,0.259424,0.0673006
XGBoost_1_AutoML_20210329_082903,0.965241,0.23461,0.970877,0.0915258,0.263373,0.0693656
GBM_5_AutoML_20210329_082903,0.964906,0.239742,0.969966,0.0870409,0.264905,0.0701745
XGBoost_grid__1_AutoML_20210329_082903_model_4,0.962885,0.24273,0.96925,0.0901471,0.267863,0.0717507
GLM_1_AutoML_20210329_082903,0.960611,0.231272,0.971269,0.0790414,0.257808,0.0664647
GBM_grid__1_AutoML_20210329_082903_model_8,0.960389,0.258108,0.965432,0.0996602,0.275576,0.0759421
XGBoost_grid__1_AutoML_20210329_082903_model_5,0.959474,0.256427,0.964174,0.104178,0.276495,0.0764492
DeepLearning_grid__1_AutoML_20210329_082903_model_3,0.95938,0.30677,0.968546,0.0882252,0.270094,0.0729507
XGBoost_grid__1_AutoML_20210329_082903_model_9,0.958839,0.257701,0.964392,0.0961642,0.276564,0.0764877
XRT_1_AutoML_20210329_082903,0.957417,0.42453,0.957402,0.0985503,0.361304,0.130541
DeepLearning_grid__2_AutoML_20210329_082903_model_2,0.95734,0.401371,0.965895,0.0972275,0.28671,0.0822026
XGBoost_2_AutoML_20210329_082903,0.957318,0.262515,0.963245,0.102214,0.281815,0.0794196
XGBoost_grid__1_AutoML_20210329_082903_model_1,0.957129,0.261017,0.96257,0.0991401,0.277521,0.0770179
DeepLearning_grid__3_AutoML_20210329_082903_model_2,0.956892,0.384009,0.965898,0.0942609,0.283829,0.0805588
GBM_grid__1_AutoML_20210329_082903_model_6,0.956395,0.273346,0.96307,0.103268,0.283161,0.0801803
XGBoost_grid__1_AutoML_20210329_082903_model_6,0.952529,0.284572,0.959867,0.102274,0.28992,0.0840536
DeepLearning_grid__1_AutoML_20210329_082903_model_1,0.951752,0.380004,0.96087,0.104313,0.292512,0.085563
XGBoost_grid__1_AutoML_20210329_082903_model_13,0.950444,0.283086,0.957551,0.116551,0.293046,0.0858758
XGBoost_grid__1_AutoML_20210329_082903_model_2,0.949555,0.295743,0.957182,0.107957,0.29618,0.0877225
DeepLearning_grid__1_AutoML_20210329_082903_model_2,0.948946,0.373294,0.958822,0.105914,0.294979,0.0870126
XGBoost_grid__1_AutoML_20210329_082903_model_8,0.94766,0.298943,0.956028,0.108468,0.297464,0.0884848
DeepLearning_1_AutoML_20210329_082903,0.946325,0.303479,0.956538,0.116059,0.300787,0.0904728
DeepLearning_grid__2_AutoML_20210329_082903_model_1,0.943384,0.387777,0.954778,0.110511,0.299259,0.0895561
DeepLearning_grid__3_AutoML_20210329_082903_model_1,0.922406,0.44785,0.940383,0.124849,0.326007,0.106281

In [142]:
test= h2o.import_file("/content/testadasyn.csv")

Parse progress: |█████████████████████████████████████████████████████████| 100%

In [144]:
test[y] = test[y].asfactor()

Age,BusinessTravel,DistanceFromHome,Education,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobSatisfaction,MaritalStatus,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Dept-Human Resouces,Dept-Research & Development,Dept-Sales,EducationField-Human Resources,EducationField-Life Sciences,EducationField-Marketing,EducationField-Medical,EducationField-Other,EducationField-Technical Degree,Healthcare Representative,Human Resources,Laboratory Technician,Manager,Manufacturing Director,Research Director,Research Scientist,Sales Executive,Sales Representative,Attrition
36,1,10,4,2,1,3,3,4,1,9980,1,0,14,3,4,0,10,3,2,10,3,9,7,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0
33,2,25,3,4,1,2,2,2,1,4320,1,0,13,3,4,0,5,2,3,5,3,0,2,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
35,3,18,4,4,0,3,2,3,3,4614,0,1,18,3,3,1,5,0,2,4,2,3,2,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1
40,2,20,4,1,1,3,3,4,3,10322,4,0,20,4,4,1,14,6,3,11,10,11,1,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0
29,3,24,2,4,1,2,1,4,1,2439,1,1,24,4,2,0,1,3,2,1,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1
30,3,3,3,3,0,3,1,3,2,2083,1,0,20,4,3,1,1,2,3,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
34,2,24,4,1,0,2,2,2,1,4599,0,1,23,4,3,0,16,2,4,15,9,10,10,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1
33,1,2,3,4,0,3,2,2,1,5147,8,0,15,3,4,0,13,2,2,11,7,1,7,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
50,1,1,3,4,0,3,2,3,3,6347,0,0,12,3,1,1,19,3,3,18,7,0,13,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
56,2,14,4,2,0,3,1,2,3,4963,9,1,18,3,1,3,7,2,3,5,4,4,3,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1

In [160]:
# Ensembled model 
a=h2o.get_model('StackedEnsemble_AllModels_AutoML_20210329_082903')

In [161]:
pr=a.predict(test)
data_as_df = pr.as_data_frame()

stackedensemble prediction progress: |████████████████████████████████████| 100%

In [162]:
y_pred=data_as_df.predict
y_test=pd.read_csv('/content/testadasyn.csv').Attrition

In [163]:
pr

predict,p0,p1
0,0.937465,0.0625354
0,0.967546,0.0324542
0,0.810049,0.189951
0,0.972352,0.0276478
1,0.0380109,0.961989
0,0.957988,0.0420116
0,0.88939,0.11061
0,0.961138,0.0388616
0,0.982417,0.0175825
0,0.932218,0.0677819

In [164]:
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.8772727272727273

In [112]:
h2o.save_model(model=a, force=True)

'/content/GBM_grid__1_AutoML_20210329_082903_model_7'

In [ ]:
gml = H2OAutoML(max_models=40, seed=1,verbosity="info",stopping_metric="misclassification")
gml.train(x=x, y=y, training_frame=train)

AutoML progress: |
10:23:26.746: Project: AutoML_20210329_102326746
10:23:26.747: Setting stopping tolerance adaptively based on the training frame: 0.0225474701184918
10:23:26.747: Build control seed: 1
10:23:26.747: training frame: Frame key: automl_training_py_488_sid_98ce    cols: 43    rows: 1967  chunks: 8    size: 76834  checksum: 1442117467069997515
10:23:26.747: validation frame: NULL
10:23:26.747: leaderboard frame: NULL
10:23:26.747: blending frame: NULL
10:23:26.747: response column: Attrition
10:23:26.747: fold column: null
10:23:26.748: weights column: null
10:23:26.748: Loading execution steps: [{XGBoost : defaults}, {GLM : defaults}, {DRF : [def_1]}, {GBM : defaults}, {DeepLearning : defaults}, {DRF : [XRT]}, {XGBoost : grids}, {GBM : grids}, {DeepLearning : grids}, {GBM : [lr_annealing]}, {XGBoost : [lr_search]}, {StackedEnsemble : defaults}]
10:23:26.749: AutoML job created: 2021.03.29 10:23:26.746
10:23:26.751: AutoML build started: 2021.03.29 10:23:26.751
10:23:26.751: AutoML: starting XGBoost_1_AutoML_20210329_102326 model training

██
10:23:33.770: New leader: XGBoost_1_AutoML_20210329_102326, auc: 0.9644849532489982
10:23:33.770: AutoML: starting XGBoost_2_AutoML_20210329_102326 model training

█
10:23:37.774: AutoML: starting XGBoost_3_AutoML_20210329_102326 model training

█
10:23:41.778: New leader: XGBoost_3_AutoML_20210329_102326, auc: 0.9691088775210597
10:23:41.778: AutoML: starting GLM_1_AutoML_20210329_102326 model training

███
10:23:48.783: AutoML: starting DRF_1_AutoML_20210329_102326 model training

█
10:23:55.791: New leader: DRF_1_AutoML_20210329_102326, auc: 0.9727697642393088
10:23:55.791: AutoML: starting GBM_1_AutoML_20210329_102326 model training

█
10:24:02.798: New leader: GBM_1_AutoML_20210329_102326, auc: 0.9736588810361726
10:24:02.799: AutoML: starting GBM_2_AutoML_20210329_102326 model training

██
10:24:09.817: AutoML: starting GBM_3_AutoML_20210329_102326 model training

██
10:24:18.824: AutoML: starting GBM_4_AutoML_20210329_102326 model training

█
10:24:30.869: New leader: GBM_4_AutoML_20210329_102326, auc: 0.9756568091872646
10:24:30.869: AutoML: starting GBM_5_AutoML_20210329_102326 model training

██
10:24:41.882: AutoML: starting DeepLearning_1_AutoML_20210329_102326 model training


10:24:44.889: AutoML: starting XRT_1_AutoML_20210329_102326 model training

███
10:24:52.916: AutoML: starting XGBoost_grid__1_AutoML_20210329_102326 hyperparameter search

████████████
10:26:07.333: AutoML: starting GBM_grid__1_AutoML_20210329_102326 hyperparameter search

████████
10:26:56.544: New leader: GBM_grid__1_AutoML_20210329_102326_model_5, auc: 0.9769072589149467

█
10:27:07.636: New leader: GBM_grid__1_AutoML_20210329_102326_model_7, auc: 0.9794469279980811

█
10:27:13.663: AutoML: starting DeepLearning_grid__1_AutoML_20210329_102326 hyperparameter search

█████████